### ISSUE TITLE
How to set ball respown position?

### ISSUE THREAD

**Issue by syKevinPeng** [lucas-emery/rocket-league-gym#11]
Hi, as the title. How do I set a ball's initial position?

**Comment by AechPro** [comment]
This functionality is not available in RLGym at the moment.

**Comment by vulnic** [comment]
Hello! 

If I'm not mistaken, the gym.reset() function is sending a header(RLGYM_RESET_GAME_STATE_MESSAGE_HEADER)+body to the RLGym.dll plugin, which somehow parses this to ask Rocket League to reset the ball/car to kickoff position. Do you foresee it being possible to add a state vector to the header/body of the message for custom ball/car resetting? We'd like to create exercises for our agent!

Thanks!

**Comment by AechPro** [comment]
State setting is possible, and is in our plans for the future. Unfortunately both of our active developers are currently occupied with other work, so it may be some time before we are able to implement that feature.

**Comment by vulnic** [comment]
Got it, thanks!
