### ISSUE TITLE
Bot difficulty

### ISSUE THREAD

**Issue by Ca3zsar** [lucas-emery/rocket-league-gym#37]
What is the default difficulty of the bot in the case of setting the spawn_opponents to True? Is there any way of changing this?

**Comment by lucas-emery** [comment]
Default difficulty is AllStar and there's no way to change it. 
But we don't recommend training against psyonix bots since they break at high speed, AllStar plays at Rookie lvl at 100x speed.
You might be better off just hardcoding a ballchaser 😄

**Comment by Ca3zsar** [comment]
Thank you very much for the response!
