### ISSUE TITLE
Doesn't get into game when run example.py

### ISSUE THREAD

**Issue by syKevinPeng** [lucas-emery/rocket-league-gym#9]
Hi,
I installed rlgym based on the instruction and tried to run the example.py.
The game is successfully started but stuck on this page.
![image](https://user-images.githubusercontent.com/48134935/116633694-305b2e00-a928-11eb-93b7-836b54c74658.png)

I have the following output in the terminal 
 ---
E:\ProgramData\Miniconda3\envs\rocketleague\python.exe E:/Study/rocketleague/playground.py
Version 0.4.1

    - Updated euler angles to match rlbot [pitch, yaw, roll] and added accessor functions
    - Bugfix: player.is_alive renamed to is_demoed
    - Added common rewards - Rolv
    - Added a reward combiner - Chainso
    - Added missing kickoff spawn
    - Fixed 2v2 and 3v3 action delivery
    - Fixed issue in 2v2 and 3v3 were blue bots would disappear over time
    - Added multi injector
Launching Rocket League, make sure bakkesmod is running.
 ---

I checked three times that my BakkesMod is working and displaying "Injected, press F2 ingame for options menu (Epic Games Version)"

**Comment by syKevinPeng** [comment]
I use python debugger to dive in the code. It looks like it stucked at line 31 in gym.py
```
self._setup_plugin_connection()
```
When I dig deeper, it actually stucked at line 100 in communicaton_handler.py
```
win32pipe.ConnectNamedPipe(self._pipe)
```

**Comment by AechPro** [comment]
Have you enabled the RLGym plugin from the Bakkesmod plugin manager in-game?

**Comment by syKevinPeng** [comment]
Thank you!!!! It'ss fixed!

**Comment by syKevinPeng** [comment]
![image](https://user-images.githubusercontent.com/48134935/117091348-f4113e80-ad28-11eb-8aa7-679c3b4ac111.png)
Does not found RLGym plugin after Rocketleague and Bakkesmod update.

**Comment by AechPro** [comment]
You will need to manually move the RLGym plugin back to the Bakkesmod folder. See the [Troubleshooting section](https://rlgym.github.io/docs-page.html#troubleshooting) of our Wiki.

**Comment by syKevinPeng** [comment]
Thank you
